### ISSUE TITLE
Create a directory on copy in deps

### ISSUE THREAD

**Issue by akremenetsky** [infraguys/genesis_devtools#30]
Example:

```yaml
    - dst: /etc/radicale/config
      path:
        src: ./images/configs/config
```
If the directory `/etc/radicale/config` doesn't exist in an image fs the following error occurs:
```shell
==> qemu.genesis-calendar: mv: cannot move '/tmp/config_1' to '/etc/radicale/config': No such file or directory
```
